version: '3'
services:
  orders:
    container_name: orders
    build: .
    ports:
      - 8083:80
    labels:
      - "traefik.http.routers.orders.rule=Host(`orders.localhost`)"
    networks:
      - traefik

networks:
  traefik:
    external: true