
version: "3" 
services:
  traefik:
    image: traefik:latest
    container_name: "traefik"
    command: --api.insecure=true --providers.docker
    ports:
      - 85:80
      - 8085:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
    labels:
      - rule = "Host(`traefik.localhost`)"

networks:
  traefik:
    external: true